


# NAME OF THE WORKFLOW THAT WILL BE SHOWN IN THE GITHUB ACTIONS TAB




name: Python Application



# SPECIFY THE EVENTS THAT WILL TRIGGER THIS WORKFLOW


on:
  push:


    branches: [ "main" ]  # TRIGGER WHEN CHANGES ARE PUSHED TO THE MAIN BRANCH


  pull_request:


    branches: [ "main" ]  # TRIGGER WHEN A PULL REQUEST IS OPENED AGAINST MAIN





# SETTING READ-ONLY PERMISSIONS FOR CONTENTS



permissions:
  contents: read

jobs:
  build:

    # SPECIFY THE OPERATING SYSTEM TO RUN THE WORKFLOW


    runs-on: ubuntu-latest




    steps:




      # STEP 1: CHECK OUT THE REPOSITORY CODE






      - uses: actions/checkout@v4





      # STEP 2: SET UP PYTHON VERSION 3.10



      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"






      # STEP 3: INSTALL DEPENDENCIES






      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip







      # STEP 4: RUN PYTHON SYNTAX CHECK






      - name: Run Python Syntax Check
        run: |
          python -m py_compile LinearProbingTable.py


